-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Omnotron Defense System", {
	[78740] = {"blue","cyan"},
	[79023] = "red",
	[79501] = {"blue","yellow"},
	[79624] = "orange",
	[79710] = "red",
	[79735] = "orange",
	[79888] = {"blue","yellow"},
	[80053] = "red",
	[80094] = "blue",
	[80157] = "blue",
	[80161] = "blue",
	[91849] = "orange",
	[91879] = {"blue","orange"},
	[92023] = {"blue","orange"},
	[92048] = {"blue","orange"},
	[92053] = "blue",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Omnotron Defense System", {
	[78740] = "long",
	[79023] = "alert",
	[79501] = "warning",
	[79624] = "info",
	[79710] = "alert",
	[79735] = "info",
	[79888] = "warning",
	[80053] = "info",
	[80094] = "alarm",
	[80161] = "underyou",
	[91879] = {"underyou","warning"},
	[92048] = "warning",
	[92053] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Magmaw", {
	[77690] = "yellow",
	[78006] = "orange",
	[78199] = {"blue","purple"},
	[78403] = {"blue","purple"},
	[78941] = "blue",
	[79011] = "green",
	[88253] = "red",
	[89773] = {"blue","purple"},
	[92134] = "blue",
	[92177] = "red",
	["adds"] = "cyan",
	["berserk"] = {"orange","red","yellow"},
	["slump"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Magmaw", {
	[78006] = "alert",
	[78941] = "warning",
	[79011] = "long",
	[88253] = "info",
	[89773] = "info",
	[92134] = "underyou",
	[92177] = "alarm",
	["adds"] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Atramedes", {
	[77611] = "cyan",
	[77612] = "orange",
	[77840] = "yellow",
	[78023] = "blue",
	[78075] = {"blue","red"},
	[92685] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Atramedes", {
	[77611] = "info",
	[77612] = "alert",
	[77840] = "warning",
	[78023] = "underyou",
	[78075] = "warning",
	[92685] = "alarm",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Chimaeron", {
	[82848] = "yellow",
	[82881] = {"blue","purple"},
	[88826] = {"green","purple"},
	[88853] = "red",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Chimaeron", {
	[82848] = "info",
	[88826] = "alert",
	[88853] = "warning",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Maloriak", {
	[77569] = {"cyan","green"},
	[77679] = "purple",
	[77699] = {"blue","yellow"},
	[77760] = {"blue","orange"},
	[77786] = {"blue","red"},
	[77896] = "red",
	[77912] = "red",
	[77987] = "purple",
	[78124] = "blue",
	[78194] = "orange",
	[78223] = "yellow",
	[78225] = "red",
	[78895] = "cyan",
	[78896] = "cyan",
	[92716] = "cyan",
	[92754] = {"green","purple"},
	[92917] = "cyan",
	[92930] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Maloriak", {
	[77569] = "info",
	[77679] = "alarm",
	[77699] = "warning",
	[77760] = "alarm",
	[77786] = "warning",
	[77896] = "alert",
	[77912] = "info",
	[78124] = "underyou",
	[78225] = "alarm",
	[92754] = "info",
	[92930] = "underyou",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Nefarian", {
	[77826] = "orange",
	[77939] = "yellow",
	[78620] = "purple",
	[78999] = "red",
	[79318] = {"blue","yellow"},
	[79339] = {"blue","orange"},
	[80734] = "orange",
	[81007] = "blue",
	[81031] = "red",
	[81272] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nefarian", {
	[77826] = "info",
	[79318] = "warning",
	[79339] = "warning",
	[80734] = "alert",
	[81007] = "underyou",
	[81031] = "alarm",
	[81272] = "alert",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Halfus Wyrmbreaker", {
	[83589] = "cyan",
	[83703] = "yellow",
	[83706] = "red",
	[83707] = "red",
	[83710] = {"cyan","orange"},
	[83908] = {"blue","purple"},
	[84030] = "yellow",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Halfus Wyrmbreaker", {
	[83703] = "alert",
	[83706] = "alarm",
	[83707] = "warning",
	[83710] = "info",
	[84030] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Valiona and Theralion", {
	[86059] = "red",
	[86369] = "blue",
	[86408] = "red",
	[86505] = "blue",
	[86622] = {"blue","orange"},
	[86788] = {"blue","yellow"},
	[86840] = "red",
	[88518] = "blue",
	[93051] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Valiona and Theralion", {
	[86059] = "alarm",
	[86369] = "warning",
	[86408] = "alarm",
	[86505] = "underyou",
	[86622] = "alarm",
	[86788] = {"alert","warning"},
	[86840] = "alert",
	[88518] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Ascendant Council", {
	[82631] = "red",
	[82660] = {"blue","red"},
	[82665] = {"blue","red"},
	[82746] = "yellow",
	[82762] = "blue",
	[82860] = "blue",
	[83067] = {"blue","red"},
	[83099] = {"blue","red"},
	[83565] = {"blue","red"},
	[83718] = "orange",
	[84913] = "orange",
	[84915] = "blue",
	[84948] = {"blue","red"},
	[92067] = {"blue","yellow"},
	[92075] = {"blue","yellow"},
	[92307] = {"blue","yellow"},
	["switch"] = "yellow",
})

BigWigs:AddSounds("Ascendant Council", {
	[82631] = "alert",
	[82746] = "alert",
	[82762] = "warning",
	[82860] = "underyou",
	[83067] = {"alarm","info"},
	[83099] = "warning",
	[83565] = {"alarm","info"},
	[83718] = "info",
	[84915] = "underyou",
	[84948] = "warning",
	[92067] = "warning",
	[92075] = "warning",
	[92307] = {"alarm","warning"},
	["switch"] = "info",
})

BigWigs:AddColors("Cho'gall", {
	[81538] = "blue",
	[81628] = "red",
	[81685] = {"blue","orange"},
	[82235] = "blue",
	[82299] = "yellow",
	[82414] = "orange",
	[82524] = "yellow",
	[82630] = {"green","yellow"},
	[91303] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["orders"] = "orange",
})

BigWigs:AddSounds("Cho'gall", {
	[81538] = "info",
	[81685] = "long",
	[82235] = "long",
	[82299] = "alert",
	[82630] = "info",
	[91303] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Sinestra", {
	[87654] = "red",
	[90045] = "orange",
	[90125] = "orange",
	[92852] = {"blue","yellow"},
	["phase"] = "green",
	["whelps"] = "red",
})

BigWigs:AddSounds("Sinestra", {
	[87654] = "alert",
	[90045] = "info",
	[92852] = "warning",
	["phase"] = "info",
})

BigWigs:AddColors("Conclave of Wind", {
	[84645] = "blue",
	[85422] = "orange",
	[86082] = "orange",
	[86193] = "red",
	[86205] = "orange",
	[86281] = "orange",
	[86307] = "red",
	[93059] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["full_power"] = "yellow",
})

BigWigs:AddSounds("Conclave of Wind", {
	[84645] = "alarm",
	[86307] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Al'Akir", {
	[87770] = {"red","yellow"},
	[87904] = "green",
	[88301] = "yellow",
	[88427] = {"blue","red"},
	[89588] = {"blue","red"},
	[89668] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
	["stormling"] = "red",
})

BigWigs:AddSounds("Al'Akir", {
	[87770] = "alert",
	[89588] = {"alarm","info"},
	[89668] = "long",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Argaloth", {
	[88942] = "red",
	[88954] = {"green","yellow"},
	[88972] = {"cyan","orange"},
	[89000] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Argaloth", {
	[88942] = {"alarm","warning"},
	[88954] = "alert",
	[88972] = {"info","long"},
	[89000] = "underyou",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Occu'thar", {
	[96884] = "yellow",
	[96913] = {"blue","red"},
	[96920] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Occu'thar", {
	[96920] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Alizabal", {
	[104936] = {"blue","yellow"},
	[105067] = {"blue","red"},
	[105784] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Alizabal", {
	[105784] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Beth'tilac", {
	[99052] = {"green","red","yellow"},
	[99497] = "green",
	[99506] = {"blue","orange"},
	[99559] = {"blue","yellow"},
	[99990] = {"blue","red"},
	["drone"] = "yellow",
	["spinner"] = "green",
})

BigWigs:AddSounds("Beth'tilac", {
	[99052] = "long",
	[99497] = "alarm",
	[99506] = "info",
	[99559] = "alarm",
	[99990] = "alert",
	["drone"] = "info",
})

BigWigs:AddColors("Lord Rhyolith", {
	[-2537] = "green",
	[97225] = "red",
	[97282] = "orange",
	[98136] = "yellow",
	[98255] = {"red","yellow"},
	[98493] = "yellow",
	[98552] = "red",
	[101304] = {"orange","red","yellow"},
	["armor"] = "green",
})

BigWigs:AddSounds("Lord Rhyolith", {
	[-2537] = "info",
	[97225] = "alarm",
	[97282] = "alert",
	[98136] = "info",
	[98255] = "alarm",
	[98493] = "info",
	[98552] = "alarm",
	[101304] = "alarm",
})

BigWigs:AddColors("Alysrazor", {
	[97128] = "blue",
	[99362] = "red",
	[99432] = "green",
	[99464] = "green",
	[99816] = {"red","yellow"},
	[99844] = {"blue","orange"},
	[99925] = {"green","orange","yellow"},
	[100024] = "blue",
	[100744] = "orange",
	["eggs"] = "green",
	["meteor"] = "yellow",
})

BigWigs:AddSounds("Alysrazor", {
	[99432] = "alert",
	[99816] = "alarm",
	[99844] = "info",
	[99925] = "alert",
	[100744] = "alert",
	["meteor"] = "alarm",
})

BigWigs:AddColors("Shannox", {
	[100002] = "yellow",
	[100129] = {"blue","green","red"},
	["berserk"] = {"orange","red","yellow"},
	["crystal"] = {"blue","orange"},
	["immolation"] = "yellow",
	["immolationyou"] = "blue",
})

BigWigs:AddSounds("Shannox", {
	[100002] = "info",
	[100129] = "alert",
	["berserk"] = "alarm",
	["crystal"] = "alarm",
	["immolationyou"] = "alarm",
})

BigWigs:AddColors("Baleroc", {
	[-2598] = "yellow",
	[99259] = "orange",
	[99516] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["torment"] = "blue",
})

BigWigs:AddSounds("Baleroc", {
	[99259] = "alert",
	[99516] = "alarm",
	["berserk"] = "alarm",
	["torment"] = "info",
})

BigWigs:AddColors("Majordomo Staghelm", {
	[97238] = "yellow",
	[98374] = "red",
	[98379] = "red",
	[98450] = "blue",
	[98476] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Majordomo Staghelm", {
	[98374] = "alert",
	[98379] = "alert",
	[98450] = "warning",
	[98476] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Ragnaros", {
	[98498] = "orange",
	[98710] = "yellow",
	[98953] = "green",
	[99172] = "red",
	[99317] = "yellow",
	[99399] = {"blue","orange"},
	[99849] = "blue",
	[100171] = "red",
	[100460] = {"blue","yellow"},
	[100479] = "green",
	[100604] = "orange",
	[100646] = "green",
	[100675] = "red",
	[100714] = "green",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Ragnaros", {
	[98498] = "alarm",
	[98710] = "info",
	[98953] = "long",
	[99172] = "alert",
	[99399] = "info",
	[99849] = "long",
	[100171] = "alert",
	[100460] = "info",
	[100675] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Morchok", {
	[103846] = "green",
	[103851] = "blue",
	[109017] = "green",
	["berserk"] = {"orange","red","yellow"},
	["crush"] = {"blue","orange"},
	["crystal_add"] = "orange",
	["crystal_boss"] = "orange",
	["stomp_add"] = "red",
	["stomp_boss"] = "red",
})

BigWigs:AddSounds("Morchok", {
	[103851] = "long",
	["berserk"] = "alarm",
	["crush"] = "info",
	["crystal_add"] = "alarm",
	["crystal_boss"] = "alarm",
})

BigWigs:AddColors("Warlord Zon'ozz", {
	[103434] = {"blue","yellow"},
	["ball"] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["bounce"] = "red",
	["darkness"] = "red",
	["drain"] = "orange",
})

BigWigs:AddSounds("Warlord Zon'ozz", {
	[103434] = "alert",
	["ball"] = "alarm",
	["berserk"] = "alarm",
	["darkness"] = "info",
})

BigWigs:AddColors("Yor'sahj the Unsleeping", {
	[-4321] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["blobs"] = "orange",
	["bolt"] = {"blue","orange"},
})

BigWigs:AddSounds("Yor'sahj the Unsleeping", {
	[-4321] = "alert",
	["berserk"] = "alarm",
	["blobs"] = "alarm",
	["bolt"] = "info",
})

BigWigs:AddColors("Hagara the Stormbinder", {
	[-4159] = "orange",
	[104448] = {"blue","red","yellow"},
	[105256] = "yellow",
	[105316] = {"blue","orange"},
	[105409] = "yellow",
	[108934] = "yellow",
	[109325] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Hagara the Stormbinder", {
	[105316] = "info",
	[109325] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Ultraxion", {
	[105925] = {"blue","yellow"},
	[106371] = "red",
	["berserk"] = {"orange","red","yellow"},
	["crystal"] = "green",
	["lighttank"] = {"blue","yellow"},
})

BigWigs:AddSounds("Ultraxion", {
	[105925] = "alarm",
	[106371] = "alert",
	["berserk"] = "alarm",
	["crystal"] = "info",
	["lighttank"] = "alarm",
})

BigWigs:AddColors("Warmaster Blackhorn", {
	[107588] = "orange",
	[108044] = "green",
	[108046] = {"blue","yellow"},
	[108076] = "blue",
	["berserk"] = {"orange","red"},
	["sapper"] = "red",
	["sunder"] = {"blue","orange"},
	["warmup"] = "green",
})

BigWigs:AddSounds("Warmaster Blackhorn", {
	[107588] = "alarm",
	[108044] = "alert",
	[108046] = "alarm",
	[108076] = "long",
	["berserk"] = "alarm",
	["sapper"] = "info",
	["sunder"] = "info",
})

BigWigs:AddColors("Spine of Deathwing", {
	[105248] = {"orange","red"},
	[105490] = {"blue","orange"},
	[105845] = "red",
	[105848] = "red",
	["residue"] = "yellow",
	["roll"] = {"blue","green","yellow"},
})

BigWigs:AddSounds("Spine of Deathwing", {
	[105845] = "info",
	["roll"] = {"alert","long"},
})

BigWigs:AddColors("Madness of Deathwing", {
	[-4351] = "green",
	[-4347] = {"blue","orange"},
	[105651] = "red",
	[106523] = "yellow",
	[106794] = "red",
	["berserk"] = {"orange","red","yellow"},
	["bigtentacle"] = "orange",
	["fragment"] = "orange",
	["hemorrhage"] = "orange",
	["impale"] = "orange",
	["last_phase"] = "yellow",
	["smalltentacles"] = "orange",
	["terror"] = "red",
})

BigWigs:AddSounds("Madness of Deathwing", {
	[-4351] = "info",
	[105651] = "long",
	[106794] = "long",
	["berserk"] = "alarm",
	["bigtentacle"] = "alert",
	["fragment"] = "alarm",
	["hemorrhage"] = "alarm",
	["impale"] = "alarm",
	["smalltentacles"] = "alarm",
})
