sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "ejOwjqXPmDWX9nmwsGceTo4d85WnIPGvtCX+yIYT6+VyfBlmHJYTGULCk6X+/mwTGYASn8KrS/VNF9AfvfQv/eJYY60yb8Y5JW0u6IpgFQpX20GiUtpMpB0xJFY6ks+lzkK8KPQWYtywepZz49coddRbmzic13sEAoPG8VK3YfX9XyJBQXIGkNtekIMmx3oyEJLW172gQhEM/N0KdlWkH7NqK0s/HqbqC8vdNebUNMqx9eazXzMw9ogOg3satKu4JDzHGPculPb/R22xX2UReNGb7IOgsHZAvh+Vwda+9s6oDmjrlDriJwzUa45Qgz0UxuhIi3vMM9YeYWEE3LtUIM94+aVOpYDnwtpQUseJbNsHJ8podixCr/SdYgm1v2jRFGArvnrtsL8S1V/4bwSG0JXpuS8JMusCK0//fl268+OTkizGk+xoeW4yAx5qGu/NsWtv0WuqHWIvQycqN682Nvyw/bgRSMWVXZuX4EV1RCnKU1DFa+bVnXwL6aInpTX0thA1XJRYKDimRw3uNWnGIpUFUNXxbQk6+NxgrllL/f4xFzpxOGkSNYNUOu0pfJlsur3glu1+P6YLKoZNzPJOF9liT/eRpaIFcOnMOtmtV5DJc5JvV8TBjh48E8INUCLJvnTSOP9rj+UQgdIRSjOxt4pKUa7NUkV9t6sRQvdwU38="
  - secure: "lTIAO+pB+U76KzdKjdgL6KgYBQtnxZrbeQJlcoRGrjr9wBKWyK90J9F3WXGDCP0nILzNdFd82WBS3ZmoTXJ2hJHJLXg2VfsB9riRX1J3q87/3zg2tqVTyStOikzO7S1vKqhyxV2SgmhtzweuoGJjmeqstMPe+JiJWITz2E5IxraSgaiirkUjP9zTDI3WGPbjToMYWQpKnbT0ADrYRkVvvBflaMFMaFgtTRkD3S1dS6ph1TpfdIDU6EYoLMsbPqRNKbipFeHQxZFQlAQsT3RDKDeq6qDgQDPt3zMGxCxF49Yr8sza3KKnniGPPMo6oSeqfoEEXPfM0K2yiCdxNZaufT/XUixeSZQyS79Rczhr5k+E9HV6FSdxb2RYftl4K1zAOimR001kvEHR5Rl6FhTMk5a5qZJa6gcfADWe0OkAozWc7Kg61AsFzQu/lxn4DA5luSitsz9KkWHKb3JF4zFakxjSkm7e4RXnQ+cTY4U2C81satL6okA8vMtTpg28J2DCmg3dN+c/usQYyI4LEJDRfgyVb+iCOVAv7WyBbxTf7CjvfM753FJKtj70ugwW5h5dOFiaSL8Ddy6IDkoZY6VUV+e6J3tke9Ks21aTQkZnqCbTp9RVniW3CoRlrdME4sJpJOZWwRALR6gVo6/6H9yipYHuWzfDbRDqIIqMPTrcxwQ="
  - secure: "bUaP59OFsvrv0ZpaNTUyutdJtbttLWsvTFDbYbNbbOx6rECazq/KnACAgbMOAZgzV4vKq2bUFrNG3pS1BG1gOOHqbRD5Gq5iAtQ901ZCBeBj9vup3gesSMHu31MXS3oyE4nMFIiwIQTp0l0ijCsTDxGNI5l+mshq5WtMFN8GfeH+k1gynFPXWs7TOFbKJf70sMnY7BbOxltuA5HBreD4xTskwfGcagR/ik1FswSkJ97i2/UvBUvGI9pZpxl+R+cPD3n/gLK1vwpbmejKNrR3DsbZGTRZSU9outzYtrWAuAW+2EvvSu0HQpT9jeh0fAxQJqbZ6G1tt0CnnVARm8vXZ0rk0JRQQltFn0C58Mtnk9fWdMf7rLZS5d7INBCrIthTPn2ltQqdzm756Afi6rPJNsHBVtzsYb3PzGJIHV1AtutFNQyz0oYhNmA2HSZkqFCd6SDEAHM+0nG0lZ33t99dvX2of+DUsYlnUtj+f5n5tGOFzuVGfgqY4D0Jr5iXCO9F9ObZr0L9ZfLI76AigjboSAR0EXwYE9aMJNNLkCQ+vIh1ZvofMPXS1xdEoUoSlrstJZoVjsreGateD+HWgRNtyRTcew+ebciza7cs1Y9DrT1Z0oPk9+N4n423VYqKqOnIEsOfky7YyPlT6NvqOzXZHRDAiYXIcbWr9y05fmAIU54="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
